# Appendix
```{r, load-packages, echo = FALSE, include = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

library(tidyverse)
library(broom.mixed)
library(lme4)
library(sjPlot)
library(papaja)
library(pander)
library(tinytex)
library(kableExtra)
library(citr)

options(tinytex.verbose = TRUE)
```

```{r, load-files}
HB_EPT <- read_csv("../Tidy Data/Heritage EPT Preterit Data.csv") %>% 
  rename(., Frequency = "Token_Main_Std", Regularity = "Reg_Numerical", Proficiency = "DELE_Std")
  
HB_FCT <- read_csv("../Tidy Data/Heritage FCT Preterit Data.csv") %>%
  rename(., Frequency = "Token_Main_Std", Regularity = "Reg_Numerical", Proficiency = "DELE_Std")

HB_Composite <- read_csv("../Tidy Data/Heritage Aggregate Preterit Data.csv") %>% 
    rename(., Frequency = "Token_Main_Std", Regularity = "Reg_Numerical", Proficiency = "DELE_Std")
```

```{r, generate-verb-averages}
HB_EPT_Modified = aggregate(HB_EPT$Response, list(HB_EPT$MainVerb), FUN = mean, na.rm = TRUE)
HB_EPT_Modified = HB_EPT_Modified %>% rename(Verb_Avg = x)
HB_EPT_Modified = left_join(HB_EPT, HB_EPT_Modified, by = c("MainVerb" = "Group.1"))

HB_FCT_Modified = aggregate(HB_FCT$Response, list(HB_FCT$MainVerb), FUN = mean, na.rm = TRUE)
HB_FCT_Modified = HB_FCT_Modified %>% rename(Verb_Avg = x)
HB_FCT_Modified = left_join(HB_FCT, HB_FCT_Modified, by = c("MainVerb" = "Group.1"))
```

```{r, generate-prof-averages}
EPT_Proficiency = aggregate(HB_EPT$Response, list(HB_EPT$Participant_ID), FUN = mean, na.rm = TRUE)
EPT_Proficiency = EPT_Proficiency %>% rename(Part_Avg = x)
EPT_Proficiency = left_join(HB_EPT, EPT_Proficiency, by = c("Participant_ID" = "Group.1"))

FCT_Proficiency = aggregate(HB_FCT$Response, list(HB_FCT$Participant_ID), FUN = mean, na.rm = TRUE)
FCT_Proficiency = FCT_Proficiency %>% rename(Part_Avg = x)
FCT_Proficiency = left_join(HB_FCT, FCT_Proficiency, by = c("Participant_ID" = "Group.1"))
```

```{r, rebind-verbavg-dataframes}
Preterit_Aggregate = rbind(HB_EPT_Modified, HB_FCT_Modified)

Preterit_Aggregate$Modality <- factor(Preterit_Aggregate$Modality,
                                             levels = c("Production", "Interpretation"))

Preterit_Proficiency <- rbind(EPT_Proficiency, FCT_Proficiency)

Preterit_Proficiency$Modality <- factor(Preterit_Proficiency$Modality,
                                           levels = c("Production", "Interpretation"))
```

```{r, generate-models}
Aggregate_Model <- glmer(Response ~ Task + Frequency * Regularity * Proficiency +
                   (1 | Participant_ID) + (1 | Item),
                 data = HB_Composite,
                 family = "binomial",
                 control = glmerControl(optimizer = "bobyqa", optCtrl = list(maxfun=3e5)))

HB_EPT_Model <- glmer(Response ~ Frequency * Regularity * Proficiency +
                   (1 | Participant_ID) + (1 | Item),
                 data = HB_EPT,
                 family = binomial,
                 control = glmerControl(optimizer = "bobyqa", optCtrl = list(maxfun=3e5)))

HB_FCT_Model <- glmer(Response ~ Frequency * Regularity * Proficiency +
                   (1 | Participant_ID) + (1 | Item),
                 data = HB_FCT,
                 family = binomial,
                 control = glmerControl(optimizer = "bobyqa", optCtrl = list(maxfun=3e5)))
```

```{r, table-for-aggregate}
Table_Aggregate <- broom.mixed::tidy(Aggregate_Model, conf.int = TRUE) %>% 
  as_tibble() %>%
  select(., -c(effect, group)) %>% 
  rename(., Predictor = "term", Estimate = "estimate", SE = "std.error", z = "statistic", p = "p.value", CILower = "conf.low", CIUpper = "conf.high") %>% 
  mutate(Predictor = recode(Predictor, `Frequency:Regularity:Proficiency` = "3-Way Interation")) %>% 
  mutate(Predictor = recode(Predictor, TaskEAPT = "Task (EPT)"))

Table_Aggregate[-c(10, 11),] %>% 
  kable(align = 'lcccccc', caption = 'Table 3. Results of GLMM for aggregate model.')
```

```{r, create-EPT-table}
Table_EPT <- broom.mixed::tidy(HB_EPT_Model, conf.int = TRUE) %>% 
  as_tibble() %>%
  select(., -c(effect, group)) %>% 
  rename(., Predictor = "term", Estimate = "estimate", SE = "std.error", z = "statistic", p = "p.value", CILower = "conf.low", CIUpper = "conf.high") %>% 
  mutate(Predictor = recode(Predictor, `Frequency:Regularity:Proficiency` = "3-Way Interation"))

Table_EPT[-c(9, 10),] %>% 
  kable(align = 'lcccccc', caption = 'Table 4. Results of GLMM for EPT.')
```

```{r, create-FCT-table}
Table_FCT <- broom.mixed::tidy(HB_FCT_Model, conf.int = TRUE) %>% 
  as_tibble() %>%
  select(., -c(effect, group)) %>% 
  rename(., Predictor = "term", Estimate = "estimate", SE = "std.error", z = "statistic", p = "p.value", CILower = "conf.low", CIUpper = "conf.high") %>% 
  mutate(Predictor = recode(Predictor, `Frequency:Regularity:Proficiency` = "3-Way Interation"))

Table_FCT[-c(9, 10),] %>% 
  kable(align = 'lcccccc', caption = 'Table 5. Results of GLMM for FCT.')
```